#!/usr/bin/env bash
set -euo pipefail

ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
OUT_DIR="$ROOT/tests/out"

generate() {
  local profile=$1
  local output=$2
  local output_dir
  local tmp

  case "$profile" in
    gnome|plasma|macos) ;;
    *) printf 'unknown profile: %s\n' "$profile" >&2; return 2 ;;
  esac

  output_dir=$(dirname -- "$output")
  mkdir -p -- "$output_dir"

  if [[ -L "$output" ]]; then
    printf 'refusing symlink output: %s\n' "$output" >&2
    return 3
  fi
  if [[ -e "$output" && ! -f "$output" ]]; then
    printf 'refusing non-file output: %s\n' "$output" >&2
    return 3
  fi

  tmp=$(mktemp -- "$output_dir/.familiar.lua.XXXXXX")
  {
    printf '%s\n' '-- Familiar — managed. Regenerated by io.github.tuxclaw.familiar; do not edit.'
    cat "$ROOT/hypr/common.lua" "$ROOT/hypr/$profile.lua"
  } > "$tmp"

  [[ $(grep -c '^local familiar =' "$tmp") -eq 1 ]]
  [[ $(grep -c '^local id =' "$tmp") -eq 1 ]]
  [[ $(grep -c '^local function surface' "$tmp") -eq 1 ]]

  if [[ -L "$output" ]]; then
    printf 'refusing symlink output: %s\n' "$output" >&2
    unlink -- "$tmp"
    return 3
  fi
  mv -fT -- "$tmp" "$output"
}

test_symlink_output_refused() {
  local test_dir
  local target
  local output

  test_dir=$(mktemp -d -- "$OUT_DIR/.symlink-test.XXXXXX")
  target=$(mktemp)
  output="$test_dir/familiar.lua"
  printf '%s\n' 'outside-sentinel' > "$target"
  ln -s -- "$target" "$output"

  if generate gnome "$output" >/dev/null 2>&1; then
    printf 'symlink output was accepted: %s\n' "$output" >&2
    return 1
  fi
  grep -qx 'outside-sentinel' "$target"

  unlink -- "$output"
  rmdir -- "$test_dir"
  unlink -- "$target"
}

if [[ ${1:-} == --profile ]]; then
  [[ $# -eq 4 && ${3:-} == --output ]] || {
    echo 'usage: tests/hypr.sh [--profile gnome|plasma|macos --output PATH]' >&2
    exit 2
  }
  generate "$2" "$4"
  exit 0
fi

[[ $# -eq 0 ]] || {
  echo 'usage: tests/hypr.sh [--profile gnome|plasma|macos --output PATH]' >&2
  exit 2
}

for profile in gnome plasma macos; do
  generate "$profile" "$OUT_DIR/familiar-$profile.lua"
done

test_symlink_output_refused
