#!/usr/bin/env bash
set -euo pipefail

ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
OUT_DIR="$ROOT/tests/out"

generate() {
  local profile=$1
  local output=$2

  case "$profile" in
    gnome|plasma|macos) ;;
    *) printf 'unknown profile: %s\n' "$profile" >&2; return 2 ;;
  esac

  mkdir -p -- "$(dirname -- "$output")"
  {
    printf '%s\n' '-- Familiar — managed. Regenerated by io.github.tuxclaw.familiar; do not edit.'
    cat "$ROOT/hypr/common.lua" "$ROOT/hypr/$profile.lua"
  } > "$output"

  [[ $(grep -c '^local familiar =' "$output") -eq 1 ]]
  [[ $(grep -c '^local id =' "$output") -eq 1 ]]
  [[ $(grep -c '^local function surface' "$output") -eq 1 ]]
}

if [[ ${1:-} == --profile ]]; then
  [[ $# -eq 4 && ${3:-} == --output ]] || {
    echo 'usage: tests/hypr.sh [--profile gnome|plasma|macos --output PATH]' >&2
    exit 2
  }
  generate "$2" "$4"
  exit 0
fi

[[ $# -eq 0 ]] || {
  echo 'usage: tests/hypr.sh [--profile gnome|plasma|macos --output PATH]' >&2
  exit 2
}

for profile in gnome plasma macos; do
  generate "$profile" "$OUT_DIR/familiar-$profile.lua"
done
