#!/usr/bin/env bash
set -euo pipefail

ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
HEADER='-- Familiar — managed. Regenerated by io.github.tuxclaw.familiar; do not edit.'

profile_ok() {
  case "${1:-}" in
    gnome|plasma|macos) return 0 ;;
    *) printf 'unknown profile: %s\n' "${1:-}" >&2; return 2 ;;
  esac
}

generate() {
  local profile=$1 output=$2 output_dir tmp
  profile_ok "$profile"
  output_dir=$(dirname -- "$output")
  mkdir -p -- "$output_dir"

  if [[ -L "$output" ]]; then
    printf 'refusing symlink output: %s\n' "$output" >&2
    return 3
  fi
  if [[ -e "$output" && ! -f "$output" ]]; then
    printf 'refusing non-file output: %s\n' "$output" >&2
    return 3
  fi

  tmp=$(mktemp -- "$output_dir/.familiar.lua.XXXXXX")
  trap 'rm -f -- "$tmp"' RETURN
  {
    printf '%s\n' "$HEADER"
    cat -- "$ROOT/hypr/common.lua" "$ROOT/hypr/$profile.lua"
  } > "$tmp"

  [[ $(grep -c '^local familiar =' "$tmp") -eq 1 ]]
  [[ $(grep -c '^local id =' "$tmp") -eq 1 ]]
  [[ $(grep -c '^local function surface' "$tmp") -eq 1 ]]

  if [[ -L "$output" ]]; then
    printf 'refusing symlink output: %s\n' "$output" >&2
    return 3
  fi
  mv -fT -- "$tmp" "$output"
  trap - RETURN
}

ensure_require() {
  local config=$1 tmp
  if [[ -L "$config" ]]; then
    printf 'refusing symlink config: %s\n' "$config" >&2
    return 3
  fi
  if [[ ! -f "$config" ]]; then
    printf 'refusing missing/non-file config: %s\n' "$config" >&2
    return 3
  fi
  if grep -Fq 'require("hypr.familiar")' "$config" || grep -Fq 'familiar:require' "$config"; then return 0; fi
  if ! grep -Fq 'require("hypr.looknfeel")' "$config"; then
    printf 'looknfeel require not found: %s\n' "$config" >&2
    return 4
  fi

  tmp=$(mktemp -- "$(dirname -- "$config")/.hyprland.lua.XXXXXX")
  trap 'rm -f -- "$tmp"' RETURN
  awk '
    { print }
    /^[[:space:]]*require\("hypr.bindings"\)/ { bindings = 1 }
    !inserted && /^[[:space:]]*require\("hypr.looknfeel"\)/ {
      if (bindings) exit 4
      print "require(\"hypr.familiar\") -- familiar:require"
      inserted = 1
    }
    END { if (!inserted) exit 4 }
  ' "$config" > "$tmp"
  if [[ -L "$config" ]]; then
    printf 'refusing symlink config: %s\n' "$config" >&2
    return 3
  fi
  mv -fT -- "$tmp" "$config"
  trap - RETURN
}

apply_live() {
  local profile=$1 home output config state previous errors
  profile_ok "$profile"
  home=${HOME:?HOME is not set}
  output="$home/.config/hypr/familiar.lua"
  config="$home/.config/hypr/hyprland.lua"
  state="$home/.local/state/familiar"
  previous="$state/familiar.lua.prev"

  if [[ -L "$output" ]]; then
    printf 'refusing symlink output: %s\n' "$output" >&2
    return 3
  fi
  if [[ -e "$output" && ! -f "$output" ]]; then
    printf 'refusing non-file output: %s\n' "$output" >&2
    return 3
  fi
  mkdir -p -- "$state"
  if [[ -f "$output" && ! -L "$output" ]]; then cp -f -- "$output" "$previous"; else : > "$previous"; fi
  generate "$profile" "$output"
  ensure_require "$config"

  if ! hyprctl reload >/dev/null; then
    restore_previous "$previous" "$output"
    printf 'failed: hyprctl reload\n' >&2
    return 5
  fi
  errors=$(hyprctl configerrors 2>&1) || {
    restore_previous "$previous" "$output"
    printf 'failed: hyprctl configerrors: %s\n' "$errors" >&2
    return 5
  }
  if [[ -n "${errors//[[:space:]]/}" ]]; then
    restore_previous "$previous" "$output"
    hyprctl reload >/dev/null 2>&1 || true
    printf 'failed: Hyprland config errors: %s\n' "$errors" >&2
    return 5
  fi
  printf 'ok\n'
}

restore_previous() {
  local previous=$1 output=$2
  if [[ -s "$previous" ]]; then cp -f -- "$previous" "$output"; else : > "$output"; fi
}

case "${1:-}" in
  --generate)
    [[ $# -eq 3 ]] || { printf 'usage: %s --generate PROFILE OUTPUT\n' "$0" >&2; exit 2; }
    generate "$2" "$3"
    ;;
  --ensure-require)
    [[ $# -eq 2 ]] || { printf 'usage: %s --ensure-require FILE\n' "$0" >&2; exit 2; }
    ensure_require "$2"
    ;;
  --apply)
    [[ $# -eq 2 ]] || { printf 'usage: %s --apply PROFILE\n' "$0" >&2; exit 2; }
    apply_live "$2"
    ;;
  *)
    printf 'usage: %s --generate PROFILE OUTPUT | --ensure-require FILE | --apply PROFILE\n' "$0" >&2
    exit 2
    ;;
esac
