#!/usr/bin/env bash
set -euo pipefail

ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
HEADER='-- Familiar — managed. Regenerated by io.github.tuxclaw.familiar; do not edit.'

profile_ok() {
  case "${1:-}" in
    gnome|plasma|macos) return 0 ;;
    *) printf 'unknown profile: %s\n' "${1:-}" >&2; return 2 ;;
  esac
}

generate() {
  local profile=$1 output=$2 output_dir tmp
  profile_ok "$profile"
  output_dir=$(dirname -- "$output")
  mkdir -p -- "$output_dir"

  if [[ -L "$output" ]]; then
    printf 'refusing symlink output: %s\n' "$output" >&2
    return 3
  fi
  if [[ -e "$output" && ! -f "$output" ]]; then
    printf 'refusing non-file output: %s\n' "$output" >&2
    return 3
  fi

  tmp=$(mktemp -- "$output_dir/.familiar.lua.XXXXXX")
  trap 'rm -f -- "$tmp"' RETURN
  {
    printf '%s\n' "$HEADER"
    cat -- "$ROOT/hypr/common.lua" "$ROOT/hypr/$profile.lua"
  } > "$tmp"

  [[ $(grep -c '^local familiar =' "$tmp") -eq 1 ]]
  [[ $(grep -c '^local id =' "$tmp") -eq 1 ]]
  [[ $(grep -c '^local function surface' "$tmp") -eq 1 ]]

  if [[ -L "$output" ]]; then
    printf 'refusing symlink output: %s\n' "$output" >&2
    return 3
  fi
  mv -fT -- "$tmp" "$output"
  trap - RETURN
}

ensure_require() {
  local config=$1 tmp
  if [[ -L "$config" ]]; then
    printf 'refusing symlink config: %s\n' "$config" >&2
    return 3
  fi
  if [[ ! -f "$config" ]]; then
    printf 'refusing missing/non-file config: %s\n' "$config" >&2
    return 3
  fi
  if grep -Fq 'require("hypr.familiar")' "$config" || grep -Fq 'familiar:require' "$config"; then return 0; fi
  if ! grep -Fq 'require("hypr.looknfeel")' "$config"; then
    printf 'looknfeel require not found: %s\n' "$config" >&2
    return 4
  fi

  tmp=$(mktemp -- "$(dirname -- "$config")/.hyprland.lua.XXXXXX")
  trap 'rm -f -- "$tmp"' RETURN
  awk '
    { print }
    /^[[:space:]]*require\("hypr.bindings"\)/ { bindings = 1 }
    !inserted && /^[[:space:]]*require\("hypr.looknfeel"\)/ {
      if (bindings) exit 4
      print "require(\"hypr.familiar\") -- familiar:require"
      inserted = 1
    }
    END { if (!inserted) exit 4 }
  ' "$config" > "$tmp"
  if [[ -L "$config" ]]; then
    printf 'refusing symlink config: %s\n' "$config" >&2
    return 3
  fi
  mv -fT -- "$tmp" "$config"
  trap - RETURN
}

guard_file() {
  if [[ -L "$1" || ( -e "$1" && ! -f "$1" ) ]]; then
    printf 'refusing symlink/non-file: %s\n' "$1" >&2
    return 3
  fi
}

atomic_copy() (
  local source=$1 output=$2 tmp
  guard_file "$source" || exit 3
  [[ -f "$source" ]] || exit 3
  guard_file "$output" || exit 3
  tmp=$(mktemp -- "${output%/*}/.familiar-copy.XXXXXX") || exit 3
  trap 'rm -f -- "$tmp"' EXIT
  cp -- "$source" "$tmp" || exit 3
  guard_file "$output" || exit 3
  mv -fT -- "$tmp" "$output"
)

apply_live() (
  local profile=$1 familiar_home output config state previous errors transaction
  local mutated=0 had_output=0
  profile_ok "$profile"
  familiar_home=${HOME:?HOME is not set}
  output="$familiar_home/.config/hypr/familiar.lua"
  config="$familiar_home/.config/hypr/hyprland.lua"
  state="$familiar_home/.local/state/familiar"
  previous="$state/familiar.lua.prev"

  guard_file "$output"
  guard_file "$config"
  [[ -f "$config" ]]
  guard_file "$previous"
  transaction=$(mktemp -d -- "${config%/*}/.familiar-apply.XXXXXX")
  finish_apply() {
    local status=$?
    trap - EXIT
    if (( status != 0 && mutated )); then
      atomic_copy "$transaction/config.before" "$config" || status=5
      if (( had_output )); then
        atomic_copy "$transaction/output.before" "$output" || status=5
      elif guard_file "$output"; then
        rm -f -- "$output"
      else
        status=5
      fi
      hyprctl reload >/dev/null 2>&1 || true
    fi
    rm -rf -- "$transaction"
    exit "$status"
  }
  trap finish_apply EXIT
  cp -- "$config" "$transaction/config.before"
  cp -- "$config" "$transaction/config.after"
  # Validate and stage require insertion before replacing either live file.
  ensure_require "$transaction/config.after"
  generate "$profile" "$transaction/output.after"
  if [[ -f "$output" ]]; then
    had_output=1
    cp -- "$output" "$transaction/output.before"
  else
    : > "$transaction/output.before"
  fi
  mkdir -p -- "$state"
  atomic_copy "$transaction/output.before" "$previous"
  mutated=1
  atomic_copy "$transaction/output.after" "$output"
  atomic_copy "$transaction/config.after" "$config"

  if ! hyprctl reload >/dev/null; then
    printf 'failed: hyprctl reload\n' >&2
    exit 5
  fi
  errors=$(hyprctl configerrors 2>&1) || {
    printf 'failed: hyprctl configerrors: %s\n' "$errors" >&2
    exit 5
  }
  if [[ -n "${errors//[[:space:]]/}" ]]; then
    printf 'failed: Hyprland config errors: %s\n' "$errors" >&2
    exit 5
  fi
  printf 'ok\n'
)

case "${1:-}" in
  --generate)
    [[ $# -eq 3 ]] || { printf 'usage: %s --generate PROFILE OUTPUT\n' "$0" >&2; exit 2; }
    generate "$2" "$3"
    ;;
  --ensure-require)
    [[ $# -eq 2 ]] || { printf 'usage: %s --ensure-require FILE\n' "$0" >&2; exit 2; }
    ensure_require "$2"
    ;;
  --apply)
    [[ $# -eq 2 ]] || { printf 'usage: %s --apply PROFILE\n' "$0" >&2; exit 2; }
    apply_live "$2"
    ;;
  *)
    printf 'usage: %s --generate PROFILE OUTPUT | --ensure-require FILE | --apply PROFILE\n' "$0" >&2
    exit 2
    ;;
esac
